### PR TITLE
Add note about passing ES6 arrow functions

### PR DESCRIPTION
**Pull request by michielbdejong**
This note would have helped me to figure out what's happening. It's also a nice opportunity to evangelize and educate about ES6. :)

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks again for the PR! Definitely agree that we need to document this behavior, as I can see it becoming a pretty common question. :)

Could probably be extended to mention all mocha functions? Since this would apply to TDD interface functions, as well as the other BDD functions like `it` and hooks like `before`, etc. For example, you can't do:

``` javascript
it('test', () => {
  this.skip();
});
```

**Comment by michielbdejong** [comment]
I tried to keep it short and relevant to the context, right under the `this.slow();` snippet. I think people can generalize once you put them on the right track. If you want to make it longer then maybe it should be moved out of the 'Dynamically Generating Tests' -> 'Test duration' section, and become its own little header?

**Comment by danielstjules** [comment]
I like that idea :) Maybe a section on ES6?

**Comment by michielbdejong** [comment]
Are there any other ES6 considerations apart from this one about arrow functions and the one that's already there, `Working with Promises`? (I can't think of anything that would change because of classes, for instance, or because of let/const)

**Comment by danielstjules** [comment]
Not that I'm aware of. And sorry for the trouble!

**Comment by ianfixes** [comment]
> This note would have helped me to figure out what's happening. 

Me too.

**Comment by michielbdejong** [comment]
Put it in its own section as suggested by reviewer, and rebased.

**Comment by danielstjules** [comment]
Thanks!

**Pull request merged**
