### PR TITLE
Added http://unexpected.js.org/ as an assertion library

### PR DESCRIPTION
**Pull request by sunesimonsen**
At this point I think that unexpected is more than ready to be on the front page of the best testing framework in javascript-land. It would mean the world to us, if you merge this.

Kind regards
Sune

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@boneskull it would mean a lot for us if you considered allowing unexpected on the Mocha page. If that request is rejected I would like to know what we need to achieve for it to happen?

Kind regards
Sune

**Comment by sunesimonsen** [comment]
@jbnicolai could you guys at least consider it :-)

Have a great weekend.

**Comment by jbnicolai** [comment]
@sunesimonsen sorry for the silence w.r.t. this issue! Definitely looks good to me :-) pinging @mochajs/mocha

**Comment by sunesimonsen** [comment]
@jbnicolai thanks

**Comment by dasilvacontin** [comment]
LGTM :rocket:. I'll try it for some personal projects too. (sorry for the wait)

**Comment by sunesimonsen** [comment]
@dasilvacontin thanks, head by our gitter channel if you have any problems using it.

**Comment by dasilvacontin** [comment]
@sunesimonsen Will do, thanks :)

**Comment by boneskull** [comment]
tyvm

**Comment by sunesimonsen** [comment]
Awesome, thanks!

**Comment by danielstjules** [comment]
:clap:

**Comment by hellboy81** [comment]
Feature request: Make it as default lib!

Pull request: move on top of list ;-)

**Pull request merged**
