### PR TITLE
switch to kramdown since GH will drop support

### PR DESCRIPTION
**Pull request by boneskull**
please look [here](http://boneskull.com/mochajs.github.io/) for a sanity check.  LGTM but want another set of eyes.

### CODE REVIEW

**Comment by boneskull** [comment]
cc @mochajs/mocha this needs to be addressed before May Day

**Comment by dasilvacontin** [comment]
All differences are preferable, afaik:
- `--` is being rendered as `–` in using `kramdown`, which is a good thing imo. But they could use surrounding spaces. Take a look at the 'Pending Tests' section.
- `Here's` -> `Here’s`
- `"parameterized"` -> `“parameterized”`
- `--watch` -> `–watch`. not good, but solvable if put inside a code delimiter.
- The following block is being rendered quite differently (maybe because of your branch not being up to date with `master`) : 
  screenshot 2016-04-10 12 21 29

That was all I could spot, visually.

**Comment by dasilvacontin** [comment]
Also, `Here's` is being rendered as `Here’s` using `kramdown`, which again is preferable, I believe.

**Comment by boneskull** [comment]
@dasilvacontin fixed the `--watch` thing

**Comment by boneskull** [comment]
> The following block is being rendered quite differently (maybe because of your branch not being up to date with master) : screenshot 2016-04-10 12 21 29

This is due to a tabs/spaces disagreement; I'll fix

**Pull request merged**
