### PR TITLE
wip: contribution guidelines

### PR DESCRIPTION
**Pull request by boneskull**
[See it in action](http://boneskull.com/mochajs.github.io/contributing/)

screenshot

### CODE REVIEW

**Comment by ScottFreeCode** [comment]
Looks really nice! Just a few minor notes from me:
- https://github.com/mochajs/people -> https://github.com/orgs/mochajs/people
- "A PR which increases coverage is unlikely to be turned down."
  This means code coverage of Mocha's own tests, right? May as well spell that out explicitly for anyone looking at these guidelines who's less familiar.
- Is it possible to avoid redundancy between this copy and the contribution guidelines GitHub presents to people filing issues/PRs?
- Could use https://github.com/mochajs/mocha/labels/pr-please instead of https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Apr-please (I think they're equivalent as long as we don't have PRs with the `pr-please` label); or we could stick with the complex query format and see if there's a way to OR the label to include both `pr-please` and `pr-needs-work`?

**Comment by boneskull** [comment]
@ScottFreeCode 

> "A PR which increases coverage is unlikely to be turned down." This means code coverage of Mocha's own tests, right? May as well spell that out explicitly for anyone looking at these guidelines who's less familiar.

Code coverage of Mocha itself, yes.

> Is it possible to avoid redundancy between this copy and the contribution guidelines GitHub presents to people filing issues/PRs?

My plan is to provide a `CONTRIBUTING.md` which links to this documentation at `mochajs.org`.    [ESLint does this](https://github.com/eslint/eslint/blob/master/CONTRIBUTING.md).

I'll look at those URLs.

**Comment by ScottFreeCode** [comment]
The ESLint `CONTRIBUTING.md` is quite well organized and impressive.

**Comment by mikesherov** [comment]
👍

**Pull request closed without merging**
