### PR TITLE
Fix #41: Update favicon

### LINKED ISSUE #41: favicon needs updating

### PR DESCRIPTION
**Pull request by Alhadis**
This is how it looks:

Figure 1

However, I also tried this, which I feel looks more distinctive:

Figure 2

I've uploaded the zip file for that last one [here](https://github.com/mochajs/mochajs.github.io/files/415639/favicons.zip) if you want it. Includes some variations generated by [realfavicongenerator.net](http://realfavicongenerator.net/). =)

Figure 3.1: Android Figure 3.2: Windows
Figure 3.3: Safari

Code not included as I figured I might've been a bit excessive given what [this PR](https://github.com/mochajs/mochajs.github.io/issues/41) needed, but hey.

### CODE REVIEW

**Comment by Alhadis** [comment]
Oh yeah, and before I wipe it off my desktop, here's the [source vector](https://github.com/mochajs/mochajs.github.io/files/415668/Mocha-iOS.zip) for the iOS touch-icon. =)

**Comment by boneskull** [comment]
thanks!

dancing wallaby

**Comment by boneskull** [comment]
> Code not included as I figured I might've been a bit excessive given what this PR needed, but hey.

If you have this code, could probably use it one way or another

**Comment by boneskull** [comment]
I think I like the alternate one.  I'll see if I can rebase this to give you proper credit.

**Comment by Alhadis** [comment]
Haha, my pleasure! =)

Code is here, mate:

``` html
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32"/>
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16"/>
<link rel="manifest" href="/manifest.json"/>
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
<meta name="theme-color" content="#8d6748"/>
```

**Pull request merged**
