### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by angelicavalenta**
Update docs to include async / await example

### CODE REVIEW

**Comment by angelicavalenta** [comment]
CLA has been signed

**Comment by ScottFreeCode** [comment]
Example and description both look good to me.

We might consider making the section level `####` instead of `###` so it's a subsection of the Promises subsection, since async/await is syntactic sugar for promises (at least as far as I'm aware at this point -- I've heard some developers discussing how they'd like it generalized to more than just promises, but what I've heard so far sounds like just speculation on what could be useful in the future); however, I'd rather have it in as-is than left out over that.

/cc @mochajs/core Any concerns about going ahead and merging this?

**Comment by dasilvacontin** [comment]
LGTM. And I think it's okay to have it as a separate section.

**Comment by dasilvacontin** [comment]
Thanks for the addition, @angelicavalenta! 😊 🎉

**Pull request merged**
